services:

  member-service:
    image: openjdk:22-jdk-oracle
    container_name: memberimage
    ports:
      - "${SERVICE_PORT1}:8080"
      - "${SERVICE_PORT2}:8000"
    expose:
      - "8003"
    depends_on:
      - memberservice-db
    networks:
      - greenspot-net
    volumes:
      - ./build/libs/MemberService-v0.0.9.jar:/app/app.jar
    working_dir: /app
    entrypoint: java -Xdebug -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8000 -jar /app/app.jar

  memberservice-db:
    image: mongo:latest
    container_name: memberservicedb
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - mongo_memberservice:/etc/mongo
      - mongo_memberservice_data:/data/db
      - mongo_memberservice_config:/data/configdb
    networks:
      - greenspot-net

networks:
  greenspot-net:
    name: greenspot_net

volumes:
    mongo_memberservice:
    mongo_memberservice_data:
    mongo_memberservice_config:
