services:

  member-service:
    image: openjdk:22-jdk-oracle
    container_name: memberimage
    ports:
      - "${SERVICE_PORT1}:8080"
      - "${SERVICE_PORT2}:8000"
    env_file:
      - .env
    depends_on:
      - member-db
    networks:
      - greenspot-net
    volumes:
      - ./build/libs/MemberService-v1.0.6.jar:/app/app.jar
    working_dir: /app
    entrypoint: java -Xdebug -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8000 -jar /app/app.jar

  member-db:
    image: mongo:latest
    container_name: memberdb
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - mongo_member:/etc/mongo
      - mongo_member_data:/data/db
      - mongo_member_config:/data/configdb
    networks:
      - greenspot-net

networks:
  greenspot-net:
    name: greenspot_net

volumes:
    mongo_member:
    mongo_member_data:
    mongo_member_config:
