services:

  resource-service:
    image: openjdk:22-jdk-oracle
    container_name: resourceimage
    ports:
      - "${SERVICE_PORT1}:8080"
      - "${SERVICE_PORT2}:8000"
    env_file:
      - .env
    depends_on:
      - resource-db
    networks:
      - greenspot-net
    volumes:
      - ./build/libs/ResourceService-v1.1.8.jar:/app/app.jar
    working_dir: /app
    entrypoint: java -Xdebug -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8000 -jar /app/app.jar

  resource-db:
    image: mongo:latest
    container_name: resourcedb
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - mongo_resource:/etc/mongo
      - mongo_resource_data:/data/db
      - mongo_resource_config:/data/configdb
    networks:
      - greenspot-net

networks:
  greenspot-net:
    name: greenspot_net

volumes:
    mongo_resource:
    mongo_resource_data:
    mongo_resource_config:
